namespace assets {
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannonball = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_brick_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_breakable_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_empty = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_upper_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_upper_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_rail_vertical = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_rail_horizontal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_west_pink = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_west_orange = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_west_green = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_east_pink = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_east_orange = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_east_green = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_steel_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_stone_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_breakable_block_large_nw = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_breakable_block_large_ne = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_brick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_crosshatch = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_breakable_block_large_sw = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_breakable_block_large_se = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_dirt_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_dirt_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_ladder = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_battery = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_heart = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_empty_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_green_arrow_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_green_arrow_south = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_green_arrow_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_green_arrow_north = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_orange_arrow_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_orange_arrow_south = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_orange_arrow_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_orange_arrow_north = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_character_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_character_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_character_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_character_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_number_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_number_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_number_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_number_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_spike_north = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_spike_south = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_spike_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_spike_east = image.ofBuffer(hex``);
}
