namespace assets {
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannonball = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_horizontal0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_horizontal1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_horizontal2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_horizontal3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_horizontal4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_horizontal5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_horizontal6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_horizontal7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_vertical0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_vertical1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_vertical2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_vertical3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_vertical4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_vertical5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_vertical6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_vertical7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_large19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_small0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_small1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_small2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const effect_small3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_horizontal17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_vertical17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_idle0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_idle1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_idle2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_idle3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_idle4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_idle5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_idle6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_idle7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_idle8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_idle9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_walk0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_walk1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_walk2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_walk3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_walk4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_walk5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_walk6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_walk7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_walk8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const player_walk9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_wall_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_brick_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_breakable_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_empty = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_door_upper_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_door_upper_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_rail_vertical = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_rail_horizontal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_door_lower_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_door_lower_west_pink = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_door_lower_west_orange = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_door_lower_west_green = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_door_lower_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_door_lower_east_pink = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_door_lower_east_orange = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_door_lower_east_green = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_wall_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_wall_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_steel_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_stone_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_breakable_block_large_nw = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_breakable_block_large_ne = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_wall_brick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_wall_crosshatch = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_breakable_block_large_sw = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_breakable_block_large_se = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_wall_dirt_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_wall_dirt_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_ladder = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_battery = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_heart = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_empty_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_green_arrow_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_green_arrow_south = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_green_arrow_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_green_arrow_north = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_orange_arrow_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_orange_arrow_south = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_orange_arrow_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_orange_arrow_north = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_character_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_character_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_character_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_character_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_number_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_number_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_number_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_number_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_spike_north = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_spike_south = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_spike_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="?tile misc"
    export const tile_spike_east = image.ofBuffer(hex``);
}
