namespace sprites.assets {
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_cannon_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_cannon_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_cannon_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_cannon_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_cannon_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_cannon_5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_cannon_6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannon_cannon_7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const cannonball_cannonball = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door_door_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door_door_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door_door_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door_door_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door_door_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door_door_5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door_door_6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door_door_7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door_door_8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const door_door_9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk_jerk_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk_jerk_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk_jerk_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk_jerk_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk_jerk_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk_jerk_5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk_jerk_6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk_jerk_7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk_jerk_8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const jerk_jerk_9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_laser_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_laser_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_laser_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_laser_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_laser_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_laser_5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_laser_6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_laser_7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const laser_laser_8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_brick_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_breakable_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_empty = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_upper_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_upper_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_rail_vertical = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_rail_horizontal = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_west_pink = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_west_orange = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_west_green = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_east_pink = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_east_orange = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_door_lower_east_green = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_steel_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_stone_block = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_breakable_block_large_nw = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_breakable_block_large_ne = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_brick = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_crosshatch = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_breakable_block_large_sw = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_breakable_block_large_se = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_dirt_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_wall_dirt_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_ladder = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_battery = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_heart = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_empty_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_green_arrow_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_green_arrow_south = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_green_arrow_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_green_arrow_north = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_orange_arrow_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_orange_arrow_south = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_orange_arrow_east = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_orange_arrow_north = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_character_0 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_character_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_character_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_character_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_number_1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_number_2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_number_3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_number_4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_spike_north = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_spike_south = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_spike_west = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=image.__imagePicker
    export const tile_spike_east = image.ofBuffer(hex``);
}
